### PR TITLE
Add an active boolean field and use variant_uid for the lookup_field.

### PR DESCRIPTION
**Pull request by ralphbean**
This is for https://pagure.io/fm-orchestrator/issue/407

### CODE REVIEW

**Comment by mprahl** [comment]
+0.5 from me since I don't know Django, but comparing it to the other code in this project it looks good to me.

**Comment by ralphbean** [comment]
@hanzz can you have a look at this too?

**Comment by jankaluza** [comment]
+1

**Comment by ralphbean** [comment]
Thanks guys!

**Pull request merged**
